name: CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest]
    steps:
    - uses: actions/checkout@v5
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v5
      with:
        dotnet-version: 9.0.x
    - name: Install dependencies
      run: dotnet restore
      working-directory: src
    - name: Build
      run: dotnet build --configuration Release --no-restore
      working-directory: src
    - name: Test
      run: dotnet test --no-restore --verbosity normal --collect "XPlat Code Coverage" --results-directory TestResults/
      working-directory: src
    - name: Codecov
      uses: codecov/codecov-action@v5
      with:
        token: ${{ secrets.CODECOV_TOKEN }}
        directory: src/TestResults/
